// EOS Traction Tool — Deployment Configuration
// Generated by the in-app Setup Wizard on 2026-07-01.
// Upload this file to the SAME folder as index.html in your GitHub Pages repo.
// This file is never overwritten by future index.html updates — safe to keep.
window.EOS_CONFIG = {
    setupComplete: true,
    companyName: "Intelligent Investing LLC",
    googleClientId: "827608282435-4d263lgsjtclrqogahmi6bdebsd4lju5.apps.googleusercontent.com",
    allowedDomain: "investedwithyou.com",
    sharedSheetId: "1YV93QI3f-3Eww-TUxFnP3uZmhPpXZiV4KVqWAsdU3pc",
    bootstrapWebAppUrl: "https://script.google.com/macros/s/AKfycbyoIlqnHljqXJ0hyNBY9D3YTXDA_oi_gG7ewGeGWHspvooknPIgGOrc2-45jx2d8iLk/exec",
    // Marketing-tab access control (2026-07-23, EOS_MASTER_SUMMARY.md Sec 5.3).
    // supabaseAnonKey is a PUBLISHABLE key by design - safe in client-side code.
    // Row Level Security in the database is the real security boundary, not key secrecy.
    supabaseUrl: "https://fhmvvnwubzqfgdokenog.supabase.co",
    supabaseAnonKey: "sb_publishable_4dwVyTyhpdzjsaMDry-68Q_Ifq45T7S",
    // Notifications (v5.27.0, schema.sql PART 8): the PUBLIC half of the Web Push signing
    // pair. Safe in the browser by design - it only lets a phone recognise pushes signed
    // by the matching private key, which lives as a secret on the push Edge Function.
    vapidPublicKey: "BBRwJ8WxUrYmxT8qlUgy4LdqFXWEVxDIt3bXYqr6roM0b4NmbJMAzA2ginG8E6_yUeEZyFIDOorB0EULoKvUtm4"
};
